watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
    blur_effect:
      enabled: true
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
          "home",
          "glazewm_workspaces",
          "workspace_separator",
          "active_window",
      ]
      center: [
          "clock",
        ]
      right: [
          "language",
          "memory",
          "cpu",
          "wifi",
          "volume",
          "battery",
          "power_menu"
      ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "~\\Downloads"}
        - { title: "Documents", path: "~\\Documents"}
        - { title: "Pictures", path: "~\\Pictures"}
        - { title: "Videos", path: "~\\Videos"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "small"
      border_color: "#7aa2f7"
      alignment: "left"
      offset_left: 4
      offset_top: 0
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_if_offline: true
      app_icons:
        enabled_populated: true
        enabled_active: true
        enabled_focused: true
        size: 14
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "KomorebiWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: true
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span class='icon memory-icon'>\ueea0</span> {virtual_mem_percent}%"
      label_alt: "<span class='icon memory-icon'>\ueea0</span> {virtual_mem_outof}"
      update_interval: 10000
      hide_decimal: true
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span class='icon cpu-icon'>\ueea1</span> {info[percent][total]}%"
      label_alt: "<span class='icon cpu-icon'>\ueea1</span> {info[freq][current]:.0f} MHz"
      update_interval: 1000
      hide_decimal: true
      callbacks:
        on_left: "toggle_label"
  language:
    type: "yasb.custom.CustomWidget"
    options:
      label: "{data}"
      label_alt: "{data}"
      label_placeholder: "--"
      class_name: "ime-language-widget"
      exec_options:
        run_cmd: "autohotkey.exe %USERPROFILE%\\.config\\yasb\\ime-language.ahk"
        run_interval: 1000
        return_format: "string"
        hide_empty: false
        use_shell: true
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 50
      max_length_ellipsis: "..."
      monitor_exclusive: true
  workspace_separator:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\u2502"
      class_name: "workspace-separator"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span>{%H:%M}"
      label_alt: "<span>\uf017</span>{%A, %B %d. %Y %H:%M}"
      locale: "en_US"
      timezones: []
      calendar:
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        offset_top: 0
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span class='icon wifi-icon'>{wifi_icon}</span> {wifi_strength}%"
      label_alt: "<span class='icon wifi-icon'>{wifi_icon}</span> {wifi_name} {wifi_strength}%"
      ethernet_label: "<span class='icon ethernet-icon'>{wifi_icon}</span>"
      ethernet_label_alt: "<span class='icon ethernet-icon'>{wifi_icon}</span> {wifi_name}"
      ethernet_icon: "\ue839"
      update_interval: 5000
      callbacks:
        on_left: "exec quick_settings"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons: [
        "\ue871",  # Icon for 0% strength
        "\ue872",  # Icon for 1-20% strength
        "\ue873",  # Icon for 21-40% strength
        "\ue874",  # Icon for 41-80% strength
        "\ue701"   # Icon for 81-100% strength
      ]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span class='icon volume-icon'>{icon}</span> {level}"
      label_alt: "{volume}"
      icons:
        - "\ue74f"  # Icon for muted
        - "\ue992"  # Icon for 0-10% volume
        - "\ue993"  # Icon for 11-30% volume
        - "\ue994"  # Icon for 31-60% volume
        - "\ue995"  # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        direction: "down"
        offset_top: 0
      callbacks:
        on_right: "toggle_mute"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span class='icon battery-icon'>{icon}</span>{percent}%"
      label_alt: "<span class='icon battery-icon'>{icon}</span> {percent}% | time: {time_remaining}"
      #hide_unsupported: true
      status_icons:
        icon_charging: "\uea93"
        icon_critical: "\ue850"
        icon_low: "\ue852"
        icon_medium: "\ue856"
        icon_high: "\ue859"
        icon_full: "\ue83f"
      charging_options:
        icon_format: "{charging_icon}"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\ue7e8"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\ue7e8", "Shut Down"]
        restart: ["\uf305", "Restart"]
        signout: ["\uf3b1", "Sign out"]
        hibernate: ["\ue74e", "Hibernate"]
        sleep: ["\ue708", "Sleep"]
        cancel: ["", "Cancel"]
